services:
  - type: web
    name: bfhl-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: USER_FULL_NAME
        value: Palak Gusain
      - key: USER_DOB
        value: "15112005"
      - key: USER_EMAIL
        value: gusainpalak015@gmail.com
      - key: USER_ROLL_NUMBER
        value: 2311981367
